/* ===== Lim · 特效 + 留言交互 ===== */

/* ---------- ① Supabase 配置（开工前必须填！） ----------
 * 去 https://supabase.com 免费建个项目，然后：
 * 1. SQL Editor 里跑一遍下面的建表语句：
 *
 *   create table messages (
 *     id bigint generated by default as identity primary key,
 *     name text not null,
 *     content text not null,
 *     status text not null default 'pending',
 *     created_at timestamptz not null default now()
 *   );
 *   alter table messages enable row level security;
 *
 * 2. SQL Editor 再跑这两条放行策略（允许匿名读取"已通过"留言 + 写入新留言）：
 *
 *   create policy "read approved"
 *     on messages for select using (status = 'approved');
 *
 *   create policy "insert messages"
 *     on messages for insert with check (true);
 *
 * 3. 把下面的 SUPABASE_URL 和 SUPABASE_ANON_KEY 换成你项目的：
 *    项目设置 → API → Project URL 和 anon public key
 * 4. 然后去 Supabase 后台 Tables → messages，手动把垃圾/新留言的 status
 *    改成 'approved' 才会显示（自动过滤只挡明显垃圾，人工审核兜底）。
 */
var SUPABASE_URL = "https://YOUR-PROJECT.supabase.co";
var SUPABASE_ANON_KEY = "YOUR-ANON-KEY";

var GB_ENABLED = SUPABASE_URL.indexOf("YOUR-PROJECT") === -1;

/* ---------- ② 动效：AOS 滚动出现 + Typed.js 打字机 + Animate.css hover ---------- */
(function initEffects() {
  if (window.AOS) {
    AOS.init({
      once: true,      // 只播一次，滚动回来不重播，省性能
      duration: 600,
      offset: 80,
      easing: "ease-out-cubic"
    });
  }

  if (window.Typed && document.getElementById("typed")) {
    new Typed("#typed", {
      strings: [
        "「原神」提瓦特观光团 · UID 277743783",
        "「崩坏：星穹铁道」开拓者 · UID 117119074",
        "折腾 AI，让 AI 干活而不是被 AI 干",
        "写点小工具，顺便解决自己的问题",
        "白天刷题，晚上搞机，偶尔登登游戏"
      ],
      typeSpeed: 55,
      backSpeed: 26,
      backDelay: 1700,
      startDelay: 400,
      loop: true,
      smartBackspace: false
    });
  }

  // hover 小动画：Animate.css 在鼠标移入时触发一次，播完自动摘类
  function bindHoverAnim(selector, anim, iconSel) {
    document.querySelectorAll(selector).forEach(function (el) {
      var icon = el.querySelector(iconSel);
      if (!icon) return;
      el.addEventListener("mouseenter", function () {
        icon.classList.add("animate__animated", anim);
        icon.addEventListener("animationend", function done() {
          icon.classList.remove("animate__animated", anim);
          icon.removeEventListener("animationend", done);
        });
      });
    });
  }
  bindHoverAnim(".card", "animate__rubberBand", ".card-icon i");
  bindHoverAnim(".hobby-list li", "animate__heartBeat", ".hobby-ico i");
})();

/* ---------- ③ 留言渲染 ---------- */
var listEl = document.getElementById("guestbook-list");
var statusEl = document.getElementById("gb-status");

function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;")
          .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function renderMessages(rows) {
  if (!rows || rows.length === 0) {
    listEl.innerHTML = '<p class="gb-empty"><i class="fa-solid fa-couch gb-ico" aria-hidden="true"></i>还没有留言，沙发等你来抢</p>';
    return;
  }
  listEl.innerHTML = rows.map(function (r) {
    var time = new Date(r.created_at);
    var timeStr = isNaN(time.getTime())
      ? ""
      : time.toLocaleString("zh-CN", { hour12: false });
    return (
      '<div class="gb-item">' +
        '<div class="gb-head"><span class="gb-name">' + esc(r.name) + "</span>" +
        '<span class="gb-time">' + esc(timeStr) + "</span></div>" +
        '<p class="gb-text">' + esc(r.content) + "</p>" +
      "</div>"
    );
  }).join("");
}

/* ---------- ④ 自动过滤（关键词 + 频率 + 链接清洗） ---------- */
var BLOCK_WORDS = ["代开发", "加微信", "加v", "兼职", "刷单", "博彩",
  "赌博", "贷款", "办证", "发票", "外挂", "sf", "私服", "广告"];

var linkRe = /https?:\/\/|www\./i;

var recentPosts = [];

function autoFilter(name, content) {
  var text = (name + " " + content).toLowerCase();
  // 1. 敏感词
  for (var i = 0; i < BLOCK_WORDS.length; i++) {
    if (text.indexOf(BLOCK_WORDS[i].toLowerCase()) !== -1) {
      return "内容包含敏感词，已拦截";
    }
  }
  // 2. 广告链接
  if (linkRe.test(text)) {
    return "留言里不让放链接，广告党退散";
  }
  // 3. 频率限制：60 秒内同一浏览器最多发 3 条
  var now = Date.now();
  recentPosts = recentPosts.filter(function (t) { return now - t < 60000; });
  if (recentPosts.length >= 3) {
    return "发太快啦，歇口气再写";
  }
  recentPosts.push(now);
  return null;
}

/* ---------- ⑤ 提交与加载 ---------- */
var formEl = document.getElementById("guestbook-form");
var nameEl = document.getElementById("gb-name");
var textEl = document.getElementById("gb-text");

function showStatus(msg, isError) {
  statusEl.textContent = msg || "";
  statusEl.className = "guestbook-status" + (isError ? " error" : "");
}

if (!GB_ENABLED) {
  showStatus("留言区还没配置 Supabase，先在 js/main.js 顶部填上 URL 和 Key（见注释）", true);
  listEl.innerHTML = '<p class="gb-empty">留言功能待配置…</p>';
} else {
  fetch(SUPABASE_URL + "/rest/v1/messages?select=*&status=eq.approved&order=created_at.desc&limit=50", {
    headers: {
      "apikey": SUPABASE_ANON_KEY,
      "Authorization": "Bearer " + SUPABASE_ANON_KEY
    }
  })
    .then(function (res) {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.json();
    })
    .then(renderMessages)
    .catch(function (err) {
      console.error(err);
      listEl.innerHTML = '<p class="gb-empty">留言加载失败，稍后再来看看～</p>';
    });

  formEl.addEventListener("submit", function (e) {
    e.preventDefault();
    var name = nameEl.value.trim();
    var content = textEl.value.trim();
    if (!name || !content) return;

    var blocked = autoFilter(name, content);
    if (blocked) { showStatus(blocked, true); return; }

    var btn = formEl.querySelector("button");
    btn.disabled = true;
    btn.textContent = "发送中…";

    fetch(SUPABASE_URL + "/rest/v1/messages", {
      method: "POST",
      headers: {
        "apikey": SUPABASE_ANON_KEY,
        "Authorization": "Bearer " + SUPABASE_ANON_KEY,
        "Content-Type": "application/json",
        "Prefer": "return=representation"
      },
      body: JSON.stringify({ name: name, content: content, status: "pending" })
    })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(function () {
        showStatus("收到！我先审核一下，很快就能看到啦");
        nameEl.value = "";
        textEl.value = "";
      })
      .catch(function (err) {
        console.error(err);
        showStatus("发送失败，检查一下网络或 Supabase 配置", true);
      })
      .finally(function () {
        btn.disabled = false;
        btn.textContent = "发送留言";
      });
  });
}